# Generated by Django 4.1.5 on 2023-01-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
