# Generated by Django 4.1.5 on 2023-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_game_version_parent_alter_game_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.IntegerField(
                choices=[
                    ("main_game", 0),
                    ("dlc_addon", 1),
                    ("expansion", 2),
                    ("bundle", 3),
                    ("standalone_expansion", 4),
                    ("mod", 5),
                    ("episode", 6),
                    ("season", 7),
                    ("remake", 8),
                    ("remaster", 9),
                    ("expanded_game", 10),
                    ("port", 11),
                    ("fork", 12),
                    ("pack", 13),
                    ("update", 14),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.IntegerField(
                choices=[
                    ("released", 0),
                    ("alpha", 2),
                    ("beta", 3),
                    ("early_access", 4),
                    ("offline", 5),
                    ("canceled", 6),
                    ("rumored", 7),
                    ("delisted", 8),
                ]
            ),
        ),
    ]
