# Generated by Django 4.1.7 on 2023-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_note_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("message", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[("info", 1), ("warning", 2), ("error", 3)], null=True
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "db_table": "log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="gamepassconsolecatalog",
            options={
                "verbose_name": "Gamepass Console Game",
                "verbose_name_plural": "Gamepass Console Games",
            },
        ),
        migrations.AlterModelOptions(
            name="gamepasspccatalog",
            options={
                "verbose_name": "Gamepass PC Game",
                "verbose_name_plural": "Gamepass PC Games",
            },
        ),
        migrations.AlterModelOptions(
            name="pspluscatalog",
            options={
                "verbose_name": "PS Plus Game",
                "verbose_name_plural": "PS Plus Games",
            },
        ),
    ]
