# Generated by Django 4.1.7 on 2023-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_usergameset"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasedate",
            name="category",
            field=models.IntegerField(default=0),
        ),
    ]
