# Generated by Django 4.1.5 on 2023-01-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_game_checksum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            ("console", 1),
                            ("arcade", 2),
                            ("platform", 3),
                            ("operating_system", 4),
                            ("portable_console", 5),
                            ("computer", 6),
                        ]
                    ),
                ),
                ("abbreviation", models.CharField(max_length=255)),
                ("alternative_name", models.CharField(max_length=255)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField()),
                ("generation", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseDate",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.IntegerField()),
                ("m", models.IntegerField()),
                ("y", models.IntegerField()),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField()),
                (
                    "region",
                    models.IntegerField(
                        choices=[
                            ("europe", 1),
                            ("north_america", 2),
                            ("australia", 3),
                            ("new_zealand", 4),
                            ("japan", 5),
                            ("china", 6),
                            ("asia", 7),
                            ("worldwide", 8),
                            ("korea", 9),
                            ("brazil", 10),
                        ]
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.game",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.platform",
                    ),
                ),
            ],
        ),
    ]
