# Generated by Django 4.1.5 on 2023-01-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_game_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                related_name="game_platform", to="api.platform"
            ),
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("alpha_channel", models.BooleanField(default=False)),
                ("animated", models.BooleanField(default=False)),
                ("image_id", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screenshots_game",
                        to="api.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cover",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("alpha_channel", models.BooleanField(default=False)),
                ("animated", models.BooleanField(default=False)),
                ("image_id", models.CharField(max_length=255)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="covers_game",
                        to="api.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_date", models.IntegerField()),
                (
                    "change_date_category",
                    models.CharField(
                        choices=[
                            ("YYYYMMMMDD", 0),
                            ("YYYYMMMM", 1),
                            ("YYYY", 2),
                            ("YYYYQ1", 3),
                            ("YYYYQ2", 4),
                            ("YYYYQ3", 5),
                            ("YYYYQ4", 6),
                            ("TBD", 7),
                        ],
                        max_length=20,
                    ),
                ),
                ("checksum", models.UUIDField()),
                ("country", models.IntegerField()),
                ("created_at", models.IntegerField()),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("start_date", models.IntegerField()),
                (
                    "start_date_category",
                    models.CharField(
                        choices=[
                            ("YYYYMMMMDD", 0),
                            ("YYYYMMMM", 1),
                            ("YYYY", 2),
                            ("YYYYQ1", 3),
                            ("YYYYQ2", 4),
                            ("YYYYQ3", 5),
                            ("YYYYQ4", 6),
                            ("TBD", 7),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.IntegerField()),
                ("url", models.CharField(max_length=255)),
                (
                    "developed",
                    models.ManyToManyField(related_name="developed", to="api.game"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.company",
                    ),
                ),
                (
                    "published",
                    models.ManyToManyField(related_name="published", to="api.game"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covers_game",
                to="api.cover",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="screenshots",
            field=models.ManyToManyField(
                related_name="game_screenshot", to="api.screenshot"
            ),
        ),
    ]
