# Generated by Django 4.1.7 on 2023-04-03 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_gamepasscatalog_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="end_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="start_date",
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
