# Generated by Django 4.1.5 on 2023-01-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_cover_game_alter_screenshot_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="aggregated_rating",
        ),
        migrations.RemoveField(
            model_name="game",
            name="aggregated_rating_count",
        ),
        migrations.RemoveField(
            model_name="game",
            name="follows",
        ),
        migrations.RemoveField(
            model_name="game",
            name="hypes",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="game",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="game",
            name="status",
        ),
        migrations.RemoveField(
            model_name="game",
            name="total_rating",
        ),
        migrations.RemoveField(
            model_name="game",
            name="total_rating_count",
        ),
        migrations.RemoveField(
            model_name="game",
            name="version_title",
        ),
    ]
