# Generated by Django 4.1.7 on 2023-04-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_gamepasscatalog_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="game",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("id__in", [])),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="short_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="slug_catalog",
            field=models.CharField(max_length=255),
        ),
    ]
