# Generated by Django 4.1.5 on 2023-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_dummymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyModel",
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.IntegerField(
                choices=[
                    ("main_game", 0),
                    ("dlc_addon", 1),
                    ("expansion", 2),
                    ("bundle", 3),
                    ("standalone_expansion", 4),
                    ("mod", 5),
                    ("episode", 6),
                    ("season", 7),
                    ("remake", 8),
                    ("remaster", 9),
                    ("expanded_game", 10),
                    ("port", 11),
                    ("fork", 12),
                    ("pack", 13),
                    ("update", 14),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="first_release_date",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(
                null=True, related_name="game_platform", to="api.platform"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="screenshots",
            field=models.ManyToManyField(
                null=True, related_name="game_screenshot", to="api.screenshot"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="storyline",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="summary",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="updated_at",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="url",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
