# Generated by Django 4.1.5 on 2023-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_delete_dummymodel_alter_game_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cover",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
