# Generated by Django 4.1.7 on 2023-04-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_gamepasscatalog_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="short_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
