# Generated by Django 4.1.7 on 2023-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_gamepasscatalog_game_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="pspluscatalog",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
