# Generated by Django 4.1.5 on 2023-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_game_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="platforms",
        ),
        migrations.RemoveField(
            model_name="game",
            name="screenshots",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="screenshots",
            field=models.TextField(null=True),
        ),
    ]
