# Generated by Django 4.1.7 on 2023-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_game_options_alter_pspluscatalog_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pspluscatalog",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="pspluscatalog",
            name="slug_catalog",
            field=models.CharField(max_length=255),
        ),
    ]
