# Generated by Django 4.1.7 on 2023-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_pspluscatalog_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pspluscatalog",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pspluscatalog",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
