# Generated by Django 4.1.5 on 2023-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_game_created_at_alter_game_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="first_release_date",
            field=models.IntegerField(null=True),
        ),
    ]
