# Generated by Django 4.1.5 on 2023-01-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_game_first_release_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrapping",
            fields=[
                (
                    "table_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("updated_at", models.IntegerField(default=0)),
                ("last_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.IntegerField(
                choices=[
                    (0, "main_game"),
                    (1, "dlc_addon"),
                    (2, "expansion"),
                    (3, "bundle"),
                    (4, "standalone_expansion"),
                    (5, "mod"),
                    (6, "episode"),
                    (7, "season"),
                    (8, "remake"),
                    (9, "remaster"),
                    (10, "expanded_game"),
                    (11, "port"),
                    (12, "fork"),
                    (13, "pack"),
                    (14, "update"),
                ],
                null=True,
            ),
        ),
    ]
