# Generated by Django 4.1.7 on 2023-04-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_pspluscatalog_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepasscatalog",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gamepasscatalog",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
