# Generated by Django 4.1.7 on 2023-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_gamepasscatalog_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepasscatalog",
            name="start_date_console",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="gamepasscatalog",
            name="start_date_pc",
            field=models.DateField(null=True),
        ),
    ]
