# Generated by Django 4.1.5 on 2023-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_scrapping_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='alternative_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='category',
            field=models.IntegerField(choices=[('console', 1), ('arcade', 2), ('platform', 3), ('operating_system', 4), ('portable_console', 5), ('computer', 6)], null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='generation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
