# Generated by Django 4.1.7 on 2023-04-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_gamepasscatalog_start_date_console_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamepassPCCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=255)),
                ("slug_catalog", models.CharField(max_length=255)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("xbox_start_date", models.DateTimeField(auto_now_add=True)),
                ("xbox_end_date", models.DateTimeField(blank=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GamepassConsoleCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=255)),
                ("slug_catalog", models.CharField(max_length=255)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("xbox_start_date", models.DateTimeField(auto_now_add=True)),
                ("xbox_end_date", models.DateTimeField(blank=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.game",
                    ),
                ),
            ],
        ),
    ]
