# Generated by Django 4.1.5 on 2023-02-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_platform_abbreviation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="first_release_date",
            field=models.DateField(null=True),
        ),
    ]
