# Generated by Django 4.1.5 on 2023-02-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_game_first_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(null=True, to='api.platform'),
        ),
    ]
