# Generated by Django 4.1.7 on 2023-04-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_delete_gamepasscatalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("trusted", models.BooleanField()),
                ("url", models.CharField(max_length=255)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            ("official", 1),
                            ("wikia", 2),
                            ("wikipedia", 3),
                            ("facebook", 4),
                            ("twitter", 5),
                            ("twitch", 6),
                            ("instagram", 8),
                            ("youtube", 9),
                            ("iphone", 10),
                            ("ipad", 11),
                            ("android", 12),
                            ("steam", 13),
                            ("reddit", 14),
                            ("itch", 15),
                            ("epicgames", 16),
                            ("gog", 17),
                            ("discord", 18),
                        ]
                    ),
                ),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.game",
                    ),
                ),
            ],
        ),
    ]
