# Generated by Django 4.1.5 on 2023-02-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_game_releasedate_game_id_game_release_dates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasedate',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_dates',
        ),
    ]
