# Generated by Django 4.1.7 on 2023-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="website",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
