# Generated by Django 4.1.7 on 2023-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_website_created_at_alter_website_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "official"),
                    (2, "wikia"),
                    (3, "wikipedia"),
                    (4, "facebook"),
                    (5, "twitter"),
                    (6, "twitch"),
                    (8, "instagram"),
                    (9, "youtube"),
                    (10, "iphone"),
                    (11, "ipad"),
                    (12, "android"),
                    (13, "steam"),
                    (14, "reddit"),
                    (15, "itch"),
                    (16, "epicgames"),
                    (17, "gog"),
                    (18, "discord"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
