# Generated by Django 4.1.7 on 2023-04-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_website_category_alter_website_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Website",
        ),
    ]
