# Generated by Django 4.1.5 on 2023-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_releasedate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='artworks',
            field=models.TextField(null=True),
        ),
    ]
