# Generated by Django 4.1.5 on 2023-02-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_game_artworks"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="rating_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="total_rating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="total_rating_count",
            field=models.IntegerField(null=True),
        ),
    ]
