# Generated by Django 4.1.5 on 2023-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_game_rating_game_rating_count_game_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aggregated_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='aggregated_rating_count',
            field=models.IntegerField(null=True),
        ),
    ]
