# Generated by Django 4.1.5 on 2023-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_game_aggregated_rating_game_aggregated_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='follows',
            field=models.IntegerField(null=True),
        ),
    ]
